# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]

name: shiny-deploy.yaml

permissions: read-all

jobs:
  shiny-deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: >
          docker build -t social-capture-app .
      # run the docker image supply the secrets from the github secrets store.
      - name: execute
        run: >
          docker run
          -e SHINY_ACC_NAME=${{ secrets.SHINY_ACC_NAME }}
          -e TOKEN=${{secrets.TOKEN}}
          -e SECRET=${{secrets.SECRET}}
          parser-app

